server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.anlsj.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.27:3306/cloudDB03?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: beyond
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-8003
    prefer-ip-address: true
info:
  app.name: microservice-8003
  company.name: www.anlsj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$