server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.anlsj.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.27:3306/cloudDB01?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: beyond
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


